version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  stock_service:
    build:
      context: ./stock_portfolio_app/
    container_name: stock_service_container
    ports:
      - "5001:8000"  # Host: 5001 -> Container: 8000
    expose:
      - 8000
    environment:
      - MONGO_COLLECTION=stock_portfolio
      - FLASK_PORT=8000  # Internal port Flask listens to
    depends_on:
      - mongodb
    restart: always

  capgain_service:
    build:
      context: ./capital_gain_service/
    container_name: capgain_service_container
    ports:
      - "5003:8080"  # Host: 5003 -> Container: 8080
    environment:
      - FLASK_PORT=8080  # Internal port Flask listens to
      - STOCK_SERVICE_PORT=8000
      - STOCK_SERVICE_CONTAINER_NAME=stock_service_container
    depends_on:
      - stock_service
    restart: always

volumes:
  mongo-data:
