name: assignment4

# Trigger the workflow manually using the workflow_dispatch event
on:
  workflow_dispatch:

jobs:
  build:
    # The build job runs on the latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Step to check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step to set up Docker Buildx for building multi-platform images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 #latest stable version

      # Step to log in to Docker Hub using credentials stored in GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} #these are defined in the repository secrets settings
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step to build and push the stock service image to Docker Hub
      - name: build1
        uses: docker/build-push-action@v4
        with:
          context: ./stock_portfolio_app
          tags: ${{ secrets.DOCKER_USERNAME }}/stock_service:latest
          push: true

      - name: build2
        uses: docker/build-push-action@v4
        with:
          context: ./capital_gain_service
          tags: ${{ secrets.DOCKER_USERNAME }}/capgain_service:latest
          push: true

      - name: Create log file
        run: |
          echo "$(date -Iminutes)" > log.txt
      
          echo "Nadav Peled, Daniel Katz" >> log.txt
      
          if [ "${{ steps.build1.outcome }}" == "success" ] && [ "${{ steps.build2.outcome }}" == "success" ]; then
            echo "image successfully built" >> log.txt
          else
            echo "image not able to be built" >> log.txt
          fi
      
          if [ "${{ steps.start_stock_container.outcome }}" == "success" ] && [ "${{ steps.start_capgain_container.outcome }}" == "success" ]; then
            echo "Container up and running" >> log.txt
          else
            echo "Container failed to run" >> log.txt
          fi
      
          if [ "${{ steps.run_tests.outcome }}" == "success" ]; then
            echo "tests succeeded" >> log.txt
          else
            echo "tests failed" >> log.txt
          fi
        shell: bash

      - name: Upload log file
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: log.txt

  test:
    # The test job runs on the latest version of Ubuntu and depends on the build job
    runs-on: ubuntu-latest
    needs: build

    services:
      # Define a MongoDB service for the test job
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      # Step to check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step to set up and run Docker Compose
      - name: Set up Docker Compose
        run: |
          docker-compose up -d --build

      # Step to run tests using pytest
      - name: Run tests #TODO: right tests!
        run: |
          pytest

      # Step to stop Docker Compose services
      - name: Stop Docker Compose
        run: |
          docker-compose down

  query: #TODO: verify this
    # The query job runs on the latest version of Ubuntu and depends on the test job
    runs-on: ubuntu-latest
    needs: test

    services:
      # Define a MongoDB service for the query job
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      # Step to check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step to set up and run Docker Compose
      - name: Set up Docker Compose
        run: |
          docker-compose up -d --build

      # Step to run query tests using a Python script
      - name: Run query tests
        run: |
          python query_tests.py

      # Step to stop Docker Compose services
      - name: Stop Docker Compose
        run: |
          docker-compose down
